List<Map<String,dynamic>> insta =[
   {"name":"Harmonize_tz","image":"assets/harmonize.jpg","description":"Austraria get your ticket on eventbrite.com!!! coming on 10th june ...will be lit","likes":"11,409 likes","time":"23 hours ago","posts":"0","followers":"1.5M","following":"100","description1":"tembo","description2":"JESHI THE KONDE BOY"},
   {"name":"Petr_Pinchez","image":"assets/pinchez.jpeg","description":"Happy +1 to me...Its my birthday o","likes":"112,334 likes","time":"22 hours ago","posts":"0","followers":"100.5M","following":"1200","description1":"#","description2":"Legend"},
  {"name":"Official_Haaland","image":"assets/haaland.webp","description":"Its my dads birthday...help me wish @Official_alffie Haaland best wishes","likes":"2M likes","time":"23 hours ago","posts":"0","followers":"117.5M","following":"300","description1":"Mancity the champions","description2":"#Premier League golden boot",},
 {"name":"Zari_the BossLady","image":"assets/zari.jpg","description":"The bosslady mwenyewe!!!","likes":"11,409 likes","time":"23 hours ago","posts":"0","followers":"11.5M","following":"40","description1":"","description2":"The BOSS LADY"},
   {"name":"Official_Mahrez","image":"assets/mahrez.webp","description":"Its my dads birthday...help me wish @Official_alffie Haaland best wishes","likes":"500K likes","time":"23 hours ago","posts":"0","followers":"40M","following":"150","description1":"followed by Not wItI","description2":"EPL champions 2023"},
    {"name":"Official_Foden","image":"assets/foden.webp","description":"Its my dads birthday...help me wish @Official_alffie Haaland best wishes","likes":"100K likes","time":"23 hours ago","posts":"0","followers":"130K","following":"120","description1":"followed by Not wItI","description2":"EPL champions 2023"},
     {"name":"Its_Pinchez01","image":"assets/img7.gif","description":"Its my dads birthday...help me wish @Official_alffie Haaland best wishes","likes":"222200 likes","time":"23 hours ago","posts":"0","followers":"1.5M","following":"10","description1":"followed by Not wItI","description2":"Actor"},
      {"name":"Not wItI","image":"assets/pes8.jpg","description":"Its my dads birthday...help me wish @Official_alffie Haaland best wishes","likes":"111 likes","time":"23 hours ago","posts":"0","followers":"300K","following":"1040","description1":"followed by Not wItI","description2":"JESHI JINGA"},
       {"name":"Lil Huncho","image":"assets/pes10.gif","description":"Its my dads birthday...help me wish @Official_alffie Haaland best wishes","likes":"1,405 likes","time":"23 hours ago","posts":"0","followers":"1.4M","following":"1070","description1":"followed by Not wItI","description2":""},
        {"name":"Gadafi","image":"assets/imgg5.gif","description":"Its my dads birthday...help me wish @Official_alffie Haaland best wishes","likes":"100,001 likes","time":"23 hours ago","posts":"0","followers":"3.5M","following":"6000","description1":"followed by Not wItI","description2":"Musician"},
];